# Used to define the text for each answer on the survey

COLUMNS_LIST_11 = [ 'Elementary school', 'Middle school', 'High school' ]

ANSWER_TEXT = {
    57: ['One', 'Two', 'More than two'],
    58: ['Once', 'A few times', 'Often', 'Never'],
    59: ['Once', 'A few times', 'Often', 'Never'],
    60: ['Once', 'A few times', 'Often', 'Never'],
    61: ['Once', 'A few times', 'Often', 'Never'],
    62: ['Yes', 'No'],
    63: [ 'In-school', 'Out-of-school' ],
    '55': ['Yes', 'No'],
    '49': ['Yes - from police', 'Yes - from a DA/prosecutor', 'Yes - from a judge', 'No'],
    '49_4_2': ['Yes', 'No'],
    '50': ['Yes', 'No'],
    '51': ['Yes', 'No'],
    '54': ['Yes', 'No'],
    '53': ['Mostly positive', 'Mixed', 'Mostly negative'],
    '47': ['Yes', 'No'],
    '48': ['Yes', 'No'],
    '48_1_1': ['Yes, No'], 
    '48_1_2': ['Yes, No'],
    '48_1_3': ['Yes, No'],
    '37': ['Yes', 'No'],
    '38': ['Yes', 'No'],
    '39': ['Yes', 'No'],
    '40': ['Yes', 'No'],
    '40_1': ['Yes', 'No'],
    '41': ['Yes', 'No'],
    '42': ['Never', 'Sometimes', 'Often', 'Very often'],
    '43': ['Yes - for a few days', 'Yes - for a few weeks', 'No'],
    '31': ['Yes', 'No'],
    '31_1': ['Yes', 'No'],
    '33': ['Yes', 'No'],
    '33_1': ['Emotional therapy', 'Behavioral therapy', 'Speech/Language therapy', 'Physical occupational therapy', 'Other'],
    '34': ['Yes', 'No'],
    '35': ['Yes', 'No'],
    '36': ['Yes', 'No'],
    '29': ['Yes', 'No'],
    '29_1_2': ['Abuse', 'Neglect', 'Incapacitated parent/guardian', 'Unclear Reason'],
    '29_1_4': ['A week', 'A month', '2-5 months', '5 months to one year', 'Longer than one year'],
    '29_1_5': ['Yes - physically', 'Yes - emotionally', 'Yes - verbally', 'No'],
    '29_1_6': ['Yes', 'No'],
    '29_1_7': ['Yes', 'No'],
    '30': ['Yes', 'No'],
    '21': ['Yes', 'No'],
    '22': ['Yes', 'No'],
    '22_1': ['Yes', 'No'],
    '23': ['Yes', 'No', "I don't know"],
    '24': ['Yes', 'No', "I don't know"],
    '25': ['Yes', 'No', "I don't know"],
    '26': ['Yes', 'No', "I don't know"],
    '27': ['Never', 'About once per year', 'A few times a month', '2-3 times a week'],
    '28': ['Never', 'About once per year', 'A few times a month', '2-3 times a week'],
    '18': ['Yes', 'No', 'Prefer not to answer'],
    '19': ['Yes', 'No', 'Prefer not to answer'],
    '20': ['Parent', 'Other family member', 'Teacher/coach', 'Foster Care', 'Other'],
    '8': ['Black/African American', 'Asian', 'White', 'Native American', 'Native Hawaiian/Pacific Islander', 'Multi-Race', 'Middle Eastern/North African', 'Latinx', 'Prefer to self-discribe'],
    '9': ['Male', 'Female', 'Prefer to self-describe'],
    '10': ['Yes', 'No'],
    '11': ['Straight (Heterosexual)', 'Lesbian', 'Gay', 'Bisexual', 'Asexual', 'Prefer to self-describe'],
    '1': ['State Prison', 'Country Jail'],
    '2': ['Detained', 'Sentenced']
}

PAGE_COLUMNS = {
    0: ['1', '2'],
    1: ['8', '9', '10', '11'],
    2: ['18', '19', '20'],
    3: ['21', '22', '22.1', '23', '24', '25', '26', '27', '28'],
    4: ['29', '29.1.2', '29.1.4', '29.1.5', '29.1.6', '29.1.7', '30'],
    5: ['31', '31.1', '33', '33.1', '34', '35', '36'],
    6: ['37', '38', '39', '40', '40.1', '41', '42', '43'],
    7: ['47', '48', '48.1.1', '48.1.2', '48.1.3'],
    8: ['49', '49.4.2', '50', '51', '53', '54'],
    9: ['55'],
    10: [
            '57.1', '57.2', '57.3', 
            '58.1', '58.2', '58.3', 
            '59.1', '59.2', '59.3',
            '60.1', '60.2', '60.3',
            '61.1', '61.2', '61.3',
            '62.1', '62.2', '62.3',
            '63.1', '63.2', '63.3',
        ]
}